Update package.json
Keep the CommonJS format for now.
the ESModule format reports an error:
SyntaxError: The requested module '../dist/index.js' does not provide an export named 'default'